/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangePasswordForm: typeof import('./src/components/ChangePasswordForm.vue')['default']
    EnvironmentForm: typeof import('./src/components/EnvironmentForm.vue')['default']
    GroupForm: typeof import('./src/components/GroupForm.vue')['default']
    GroupFunctionsManager: typeof import('./src/components/GroupFunctionsManager.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Notifications: typeof import('./src/components/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
    UserGroupsManager: typeof import('./src/components/UserGroupsManager.vue')['default']
  }
}
