apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapivue.fullname" . }}-caddy
  labels:
    {{- include "fastapivue.labels" . | nindent 4 }}
    app.kubernetes.io/component: caddy
spec:
  type: {{ .Values.service.caddy.type }}
  ports:
    - port: {{ .Values.service.caddy.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.caddy.type "NodePort") .Values.service.caddy.nodePort }}
      nodePort: {{ .Values.service.caddy.nodePort }}
      {{- end }}
  selector:
    {{- include "fastapivue.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: caddy
