apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapivue.fullname" . }}-frontend
  labels:
    {{- include "fastapivue.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fastapivue.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
