/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangePasswordForm: typeof import('./components/ChangePasswordForm.vue')['default']
    EnvironmentForm: typeof import('./components/EnvironmentForm.vue')['default']
    GroupForm: typeof import('./components/GroupForm.vue')['default']
    GroupFunctionsManager: typeof import('./components/GroupFunctionsManager.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    Notifications: typeof import('./components/Notifications.vue')['default']
    PasswordResetForm: typeof import('./components/PasswordResetForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./components/UserForm.vue')['default']
    UserGroupsManager: typeof import('./components/UserGroupsManager.vue')['default']
    VaAlert: typeof import('vuestic-ui')['VaAlert']
    VaButton: typeof import('vuestic-ui')['VaButton']
    VaCard: typeof import('vuestic-ui')['VaCard']
    VaIcon: typeof import('vuestic-ui')['VaIcon']
    VaInput: typeof import('vuestic-ui')['VaInput']
    VaToast: typeof import('vuestic-ui')['VaToast']
  }
}
