/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'ChangePasssword.sotry': typeof import('./components/Users/ChangePasssword.sotry.vue')['default']
    'ChangePasssword.story': typeof import('./components/Users/ChangePasssword.story.vue')['default']
    ChangePassword: typeof import('./components/Users/ChangePassword.vue')['default']
    'ChangePassword.story': typeof import('./components/Users/ChangePassword.story.vue')['default']
    'ChangePassword.stry': typeof import('./components/Users/ChangePassword.stry.vue')['default']
    ChangePasswordForm: typeof import('./components/Auth/ChangePasswordForm.vue')['default']
    'ChangePasswordForm.story': typeof import('./components/Auth/ChangePasswordForm.story.vue')['default']
    EnvironmentForm: typeof import('./components/EnvironmentForm.vue')['default']
    ForgotPasswordForm: typeof import('./components/Auth/ForgotPasswordForm.vue')['default']
    'ForgotPasswordForm.story': typeof import('./components/Auth/ForgotPasswordForm.story.vue')['default']
    GroupForm: typeof import('./components/GroupForm.vue')['default']
    GroupFunctionsManager: typeof import('./components/GroupFunctionsManager.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/Auth/LoginForm.vue')['default']
    'LoginForm.story': typeof import('./components/Auth/LoginForm.story.vue')['default']
    NotificationsList: typeof import('./components/Common/NotificationsList.vue')['default']
    PasswordResetForm: typeof import('./components/Auth/PasswordResetForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./components/UserForm.vue')['default']
    UserGroupsManager: typeof import('./components/UserGroupsManager.vue')['default']
    VaApp: typeof import('vuestic-ui')['VaApp']
    VaButton: typeof import('vuestic-ui')['VaButton']
    VaButtonDropdown: typeof import('vuestic-ui')['VaButtonDropdown']
    VaCard: typeof import('vuestic-ui')['VaCard']
    VaCardContent: typeof import('vuestic-ui')['VaCardContent']
    VaCardTitle: typeof import('vuestic-ui')['VaCardTitle']
    VaCheckbox: typeof import('vuestic-ui')['VaCheckbox']
    VaCol: typeof import('vuestic-ui')['VaCol']
    VaContent: typeof import('vuestic-ui')['VaContent']
    VaIcon: typeof import('vuestic-ui')['VaIcon']
    VaInput: typeof import('vuestic-ui')['VaInput']
    VaLayout: typeof import('vuestic-ui')['VaLayout']
    VaMain: typeof import('vuestic-ui')['VaMain']
    VaMenu: typeof import('vuestic-ui')['VaMenu']
    VaMenuItem: typeof import('vuestic-ui')['VaMenuItem']
    VaNavbar: typeof import('vuestic-ui')['VaNavbar']
    VaNavbarItem: typeof import('vuestic-ui')['VaNavbarItem']
    Variant: typeof import('vuestic-ui')['Variant']
    VaRow: typeof import('vuestic-ui')['VaRow']
    VaSidebar: typeof import('vuestic-ui')['VaSidebar']
    VaSidebarItem: typeof import('vuestic-ui')['VaSidebarItem']
    VaSidebarItemContent: typeof import('vuestic-ui')['VaSidebarItemContent']
    VaSidebarItemTitle: typeof import('vuestic-ui')['VaSidebarItemTitle']
    VaTitle: typeof import('vuestic-ui')['VaTitle']
    VaToast: typeof import('vuestic-ui')['VaToast']
  }
}
